name: Hanny
favicon: null
layout_spectrum: 0.24738
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d0000'
    - '#c1baa5'
    - '#060500'
    - '#a48964'
    - '#9b4900'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
