name: Hanny
favicon: null
layout_spectrum: 0.66398
typography_spectrum: 0.36413
title: Every step gets us closer to a polio-free world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15202c'
    - '#b4b3ae'
    - '#5a5450'
    - '#ee7570'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
