name: Hanny
favicon: null
layout_spectrum: 0.73998
typography_spectrum: 0.82196
title: Every step gets us closer to a polio-free world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16110e'
    - '#63726d'
    - '#fb80ae'
    - '#bd4455'
    - '#e0e4e4'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
