name: Hanny
favicon: null
layout_spectrum: 0.672381455078721
typography_spectrum: 0.4657433470711112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4491002974100411
  lightness: 0.4734887517988682
  saturation: 0.029370296048000455
  rhythmicContrast: 0.5891244281083345
purpose: []
